export const profileDetails = [
  {
    username: 'DevMaster',
    fullName: 'Alex Codington',
    bio: 'Passionate developer with a knack for turning caffeine into code. Creating digital wonders and solving problems with elegant solutions.',
    github: 'https://www.github.com/',
    twitter: 'https://twitter.com/',
    facebook: 'https://www.facebook.com/',
    instagram: 'https://instagram.com/',
    background: '/assets/images/bg-1.jpg',
    image: '/assets/images/img-1.jpg',
  },
  {
    username: 'CodeExplorer',
    fullName: 'Sophie Hackman',
    bio: 'Explorer of new technologies and coding realms. Transforming ideas into lines of code. Always in pursuit of the next coding adventure.',
    github: 'https://www.github.com/',
    twitter: 'https://twitter.com/',
    facebook: 'https://www.facebook.com/',
    instagram: 'https://instagram.com/',
    background: '/assets/images/bg-2.jpg',
    image: '/assets/images/img-2.jpg',
  },
  {
    username: 'TechEnthusiast',
    fullName: 'Olivia Codefield',
    bio: 'Enthusiastic about all things tech. A problem solver with a passion for innovation. Turning ideas into reality through the power of code.',
    github: 'https://www.github.com/',
    twitter: 'https://twitter.com/',
    facebook: 'https://www.facebook.com/',
    instagram: 'https://instagram.com/',
    image: '/assets/images/img-3.jpg',
    background: '/assets/images/bg-3.jpg',
  },
  {
    username: 'ByteWizard',
    fullName: 'Ethan Techsmith',
    bio: 'Magician of bytes and bytes. Crafting magic with algorithms and data structures. Making the digital world a better place, one line at a time.',
    github: 'https://www.github.com/',
    twitter: 'https://twitter.com/',
    facebook: 'https://www.facebook.com/',
    instagram: 'https://instagram.com/',
    background: '/assets/images/bg-4.jpg',
    image: '/assets/images/img-4.jpg',
  },
  {
    username: 'CyberNinja',
    fullName: 'Max Secureblade',
    bio: 'Cybersecurity ninja with a mission to protect the digital realm. Expert in securing networks and defeating cyber threats. Silent, but deadly in code battles.',
    github: 'https://www.github.com/',
    twitter: 'https://twitter.com/',
    facebook: 'https://www.facebook.com/',
    instagram: 'https://instagram.com/',
    image: '/assets/images/img-1.jpg',
    background: '/assets/images/bg-1.jpg',
  },
  {
    username: 'UIUXGuru',
    fullName: 'Lily Designsmith',
    bio: 'UI/UX design guru with a keen eye for aesthetics and user experience. Crafting beautiful and intuitive interfaces that leave a lasting impression.',
    github: 'https://www.github.com/',
    twitter: 'https://twitter.com/',
    facebook: 'https://www.facebook.com/',
    instagram: 'https://instagram.com/',
    image: '/assets/images/img-2.jpg',
    background: '/assets/images/bg-2.jpg',
  },
];
